import { Database } from './schema';

export const initialData: Database = {
  users: [
    {
      id: '1',
      email: 'admin@z360virtualtours.com',
      password: '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/X4.F7gK6kPfqEQVQe', // admin123
      name: 'Admin',
      role: 'admin',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  categories: [
    {
      id: '1',
      name: 'Real Estate',
      slug: 'real-estate',
      description: 'Virtual tours for residential and commercial properties.',
      image: '/images/categories/real-estate.jpg',
      icon: 'Home',
      order: 1,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '2',
      name: 'Business Showcase',
      slug: 'business-showcase',
      description: 'Professional virtual tours for businesses and retail spaces.',
      image: '/images/categories/business.jpg',
      icon: 'Building2',
      order: 2,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '3',
      name: 'Location Showcase',
      slug: 'location-showcase',
      description: 'Virtual tours of venues, event spaces, and unique locations.',
      image: '/images/categories/location.jpg',
      icon: 'MapPin',
      order: 3,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '4',
      name: 'Hospitality',
      slug: 'hospitality',
      description: 'Virtual tours for hotels, resorts, and vacation rentals.',
      image: '/images/categories/hospitality.jpg',
      icon: 'Hotel',
      order: 4,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '5',
      name: 'Education',
      slug: 'education',
      description: 'Campus tours for schools and educational institutions.',
      image: '/images/categories/education.jpg',
      icon: 'GraduationCap',
      order: 5,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '6',
      name: 'Healthcare',
      slug: 'healthcare',
      description: 'Virtual tours for hospitals and medical facilities.',
      image: '/images/categories/healthcare.jpg',
      icon: 'Heart',
      order: 6,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '7',
      name: 'Automotive',
      slug: 'automotive',
      description: '360° tours for car dealerships and vehicle showcases.',
      image: '/images/categories/automotive.jpg',
      icon: 'Car',
      order: 7,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '8',
      name: 'Museums & Culture',
      slug: 'museums-culture',
      description: 'Virtual exhibitions and cultural space tours.',
      image: '/images/categories/museums.jpg',
      icon: 'Landmark',
      order: 8,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  tours: [],
  services: [
    {
      id: '1',
      title: '360° Photography',
      slug: '360-photography',
      description: 'Professional 360-degree photography services using state-of-the-art equipment. We capture every angle of your space with stunning clarity and detail.',
      shortDescription: 'Professional 360° photography with state-of-the-art equipment.',
      icon: 'Camera',
      image: '/images/services/photography.jpg',
      features: [
        'High-resolution 360° images',
        'Professional lighting setup',
        'HDR image processing',
        'Quick turnaround time',
      ],
      pricing: {
        startingAt: 299,
        currency: 'USD',
      },
      order: 1,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '2',
      title: 'Virtual Tour Creation',
      slug: 'virtual-tour-creation',
      description: 'Transform your 360° photos into fully interactive virtual tours with hotspots, navigation, and custom branding.',
      shortDescription: 'Interactive virtual tours with hotspots and custom branding.',
      icon: 'Globe',
      image: '/images/services/virtual-tour.jpg',
      features: [
        'Interactive hotspots',
        'Custom navigation',
        'Floor plan integration',
        'Custom branding',
      ],
      pricing: {
        startingAt: 499,
        currency: 'USD',
      },
      order: 2,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '3',
      title: '3D Dollhouse Views',
      slug: '3d-dollhouse-views',
      description: 'Create stunning 3D dollhouse views that give viewers a complete overview of your space layout.',
      shortDescription: '3D dollhouse views for complete space overview.',
      icon: 'Box',
      image: '/images/services/3d-dollhouse.jpg',
      features: [
        'Full 3D model creation',
        'Interactive dollhouse view',
        'Floor plan generation',
        'Measurement tools',
      ],
      pricing: {
        startingAt: 799,
        currency: 'USD',
      },
      order: 3,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '4',
      title: 'Drone 360° Aerials',
      slug: 'drone-360-aerials',
      description: 'Capture breathtaking aerial 360° views with our professional drone services.',
      shortDescription: 'Stunning aerial 360° photography with professional drones.',
      icon: 'Plane',
      image: '/images/services/drone.jpg',
      features: [
        'FAA certified pilots',
        '4K aerial footage',
        '360° aerial panoramas',
        'Property mapping',
      ],
      pricing: {
        startingAt: 599,
        currency: 'USD',
      },
      order: 4,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '5',
      title: 'Google Street View',
      slug: 'google-street-view',
      description: 'Get your business on Google Street View and Google Maps with certified photography.',
      shortDescription: 'Google Street View integration for increased visibility.',
      icon: 'Map',
      image: '/images/services/google-sv.jpg',
      features: [
        'Google certified photography',
        'Direct Maps integration',
        'Business listing optimization',
        'Analytics & insights',
      ],
      pricing: {
        startingAt: 399,
        currency: 'USD',
      },
      order: 5,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '6',
      title: 'VR Experience',
      slug: 'vr-experience',
      description: 'VR-ready experiences compatible with all major VR headsets for fully immersive exploration.',
      shortDescription: 'VR-ready experiences for immersive exploration.',
      icon: 'Glasses',
      image: '/images/services/vr.jpg',
      features: [
        'VR headset compatibility',
        'WebXR support',
        'Mobile VR mode',
        'Interactive elements',
      ],
      pricing: {
        startingAt: 899,
        currency: 'USD',
      },
      order: 6,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  testimonials: [],
  contactSubmissions: [],
  places: [],
  settings: {
    siteName: 'Z360 Virtual Tours',
    tagline: 'Immersive 360° Virtual Tour Experiences',
    description: 'Professional 360° virtual tour services for real estate, businesses, hospitality, and more.',
    logo: '/images/logo.svg',
    favicon: '/favicon.ico',
    contact: {
      email: 'info@z360virtualtours.com',
      phone: '+1 (555) 360-TOUR',
      address: '123 Virtual Drive',
      city: 'Los Angeles',
      state: 'CA',
      country: 'USA',
    },
    social: {
      facebook: 'https://facebook.com/z360virtualtours',
      instagram: 'https://instagram.com/z360virtualtours',
      youtube: 'https://youtube.com/z360virtualtours',
      linkedin: 'https://linkedin.com/company/z360virtualtours',
      twitter: 'https://twitter.com/z360tours',
    },
    seo: {
      defaultTitle: 'Z360 Virtual Tours | Professional 360° Virtual Tour Services',
      titleTemplate: '%s | Z360 Virtual Tours',
      defaultDescription: 'Transform your spaces into immersive 360° virtual experiences.',
      keywords: ['virtual tours', '360 photography', 'matterport', 'real estate virtual tours'],
    },
  },
};
